### ISSUE TITLE
As a grunt Task ?

### ISSUE THREAD

**Issue by mmouterde** [enigmamarketing/express-swagger-docs#1]
I'm looking for a such feature but using a Grunt task instead of an express route.
I've succeed to mock express stuff to generate swagger.json :

```
grunt.registerTask('swagger', function (target) {

    var rootdir = './app';

    var generator = require('express-swagger-docs')({directory: rootdir});
    var fs = require('fs');

    var resMock = {
      header: function () {
      },
      status: function () {
        return {
          json: function (err) {
            writeToFile(err);
          }
        };
      },
      json: function (doc) {
        writeToFile(doc);
      },
      format: function () {
      }
    };
    var reqMock = {url: '/swagger.json', method: 'GET', hostname: 'myCompany.com'};

    var nextMock = function (err) {
      writeToFile(err);
    };

    function writeToFile(content) {
      var writer = fs.createWriteStream(rootdir + '/swagger.json');
      writer.end(JSON.stringify(content));
    }

    var done = this.async();
    setTimeout(function () {
      generator(reqMock, resMock, nextMock);
      done();
    }, 10000);
  });
```

However, it really messy and I have no way to have a callback for doc-built event.
Could I make some changes (via PR) to this module to make it usable with grunt or should I make another project ?

**Comment by relvao** [comment]
Hi @mmouterde 

A PR would be well received. I see the point in using grunt instead of having a dynamic route, although, personally, I prefer to keep it as dynamic as possible.  

What is a deal breaker for me is the ability to generate both the swagger.json and a swagger.html files. We haven't yet finished the HTML part, but that was the main goal for building this module. 

Cheers, 
Tiago

**Comment by mmouterde** [comment]
You are right, this is not really the main goal of this module.
As, I just need to get my swagger file before deploying, I have just made the grunt plugin [grunt-swagger-docs](grunt-swagger-docs) to fit my needs.
thanks
